### ISSUE TITLE
Add E2E test task [local]

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-dotnet#107]
[One-Pager](https://honeycomb.quip.com/kTyJA9ueDiAa/Beestro-Testing-One-Pager)

The goal is to have a single command that can be run locally to execute the 2 E2E test
- the task should launch the example app, hit the app endpoint, and use the validator to check that the traces ended up in Honeycomb
- it may be easier to dockerize the example app, and use the images in E2E test
- the task should return a pass or fail result (could be exit code)

**Comment by bdarfler** [comment]
Icing because we're going to start with smoke/integration tests and add e2e tests in the future if we feel we still have a gap in coverage.

**Comment by vreynolds** [comment]
superseded by updated smoke test issues
