### ISSUE TITLE
List this project in the OTel Registry

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-dotnet#117]
**Is your feature request related to a problem? Please describe.**

This project is not listed in the OTel Registry which limits its discoverability.

**Describe the solution you'd like**

List this project in the OTel Registry - https://github.com/open-telemetry/opentelemetry.io#adding-a-project-to-the-opentelemetry-registry

**Describe alternatives you've considered**

**Additional context**

**Comment by JamieDanielson** [comment]
PR: https://github.com/open-telemetry/opentelemetry.io/pull/772

**Comment by JamieDanielson** [comment]
Merged!
