### ISSUE TITLE
Document Debugging

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-dotnet#118]
**Is your feature request related to a problem? Please describe.**

Debugging/troubleshooting isn't documented which puts users at a disadvantage when they run into issues.

**Describe the solution you'd like**

Document debugging/troubleshooting steps (debug logs/flags, etc.) in the main public docs.

**Describe alternatives you've considered**

**Additional context**

**Comment by JamieDanielson** [comment]
Added docs for console exporter and self-diagnostics [troubleshooting](https://docs.honeycomb.io/getting-data-in/opentelemetry/dotnet-distro/#troubleshooting) earlier this year.
