### ISSUE TITLE
Verify generated attributes match Java distro

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-opentelemetry-dotnet#119]
See https://github.com/honeycombio/honeycomb-opentelemetry-java/pull/148 for attribute list.

**Comment by cartermp** [comment]
Took a brief look at this. As far as I can tell, there isn't an analogue to `OsResource` and `ProcessRuntimeResource` in .NET like there is in Java: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry/Resources

So we can build this and attach them to our own resources in the interim I suppose?

**Comment by cartermp** [comment]
Hahaha, hoo boy. So! There are standard methods for determining things like this in .NET, like this one: https://docs.microsoft.com/en-us/dotnet/api/system.operatingsystem.ismacos?view=net-6.0&viewFallbackFrom=netstandard-2.1

But as you can see, they're not available with .NET Standard or the legacy .NET Framework. So getting parity with Java will be more involved.

**Comment by cartermp** [comment]
Another tidbit: the runtime resources for .NET are not confirmed as specified yet: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1281

(there's an entry in the spec but it's marked as a TODO)
