### ISSUE TITLE
Give an error message when configuration is missing

### ISSUE THREAD

**Issue by jessitron** [honeycombio/honeycomb-opentelemetry-dotnet#130]
**Is your feature request related to a problem? Please describe.**

yes. I tried to run an app using AddHoneycomb in .net5 (Mike, it's your sample app)
and it gave this error:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Honeycomb.OpenTelemetry.ServiceCollectionExtensions.AddHoneycomb(IServiceCollection services, HoneycombOptions options)
   at Honeycomb.OpenTelemetry.ServiceCollectionExtensions.AddHoneycomb(IServiceCollection services, IConfiguration configuration)
...
```

Not descriptive!!

When I define HONEYCOMB__APIKEY and HONEYCOMB__DATASET and SERVICE_NAME then it runs.

**Describe the solution you'd like**

A real error message telling me which env var to define.

I observe that there is better handling for this in the TracerProviderBuilderExtensions, but somehow it isn't giving me that message??

**Describe alternatives you've considered**

personally I know what to do but someone newer to this would not

**Additional context**

**Comment by jessitron** [comment]
I got this again in 0.20.0-beta

I thought we fixed this!!!
but if I do not add a Honeycomb object to appsettings.json, I get this NPE

**Comment by JamieDanielson** [comment]
At a quick glance it appears the change made in #171 was intended to address this but likely needs to be applied in other places... will use that as a guide.

@jessitron Can you be more specific about what sample app is being used to repro this error? Thanks!
