### ISSUE TITLE
options.SetDbStatement does not seem to work

### ISSUE THREAD

**Issue by filip-ivan** [honeycombio/honeycomb-opentelemetry-dotnet#169]
Hello,
I am trying to get the DB statement to be sent to Honeycomb, but with no success. 
This is an ASP.NET (.NET Framework v4.6.1+) app. I wonder if this is a bug or if I am doing something wrong...

```
   protected void Application_Start()
        {
            _tracerProvider = Sdk.CreateTracerProviderBuilder()
                .AddHoneycomb(new HoneycombOptions
                {
                    ServiceName = {},
                    ApiKey = "{}",
                    Dataset = {},
                    ConfigureSqlClientInstrumentationOptions = options =>
                    {
                        options.SetDbStatement = true;
                    },
                    InstrumentSqlClient = true

                })
                .AddConsoleExporter()
                .Build();
...
```

**Comment by robbkidd** [comment]
Hi, @filip-ivan!

`ConfigureSqlClientInstrumentationOptions` and `InstrumentSqlClient` are not part of the `HoneycombOptions` interface. Those are methods on the `TracerProviderBuilder`. I think you'll have more success† if you move those method calls to the same level as `AddConsoleExporter()` on the builder itself.

† Or at least _different_ errors which are a sort of progress)
