### ISSUE TITLE
Adding Honeycomb exporter removes "deployment.environment" resource attribute

### ISSUE THREAD

**Issue by object** [honeycombio/honeycomb-opentelemetry-dotnet#185]
**Versions**

- .NET 5.0
- Honeycomb OpenTelemetry Distribution: 0.20.0-beta

**Steps to reproduce**

1. Use the following setup:

```
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
    .AddSource(serviceName)
    .SetResourceBuilder(
        ResourceBuilder.CreateDefault()
            .AddAttributes(new Dictionary<string, object>
            {
                {"deployment.environment", "production"}
            })
            .AddService(serviceName: serviceName, serviceVersion: serviceVersion))
    .AddHttpClientInstrumentation()
    .AddJaegerExporter(o =>
    {
        o.AgentHost = "localhost";
        o.AgentPort = 6831;
    })
    .AddConsoleExporter()
    .AddHoneycomb(o =>
    {
        o.ServiceName = serviceName;
        o.ApiKay = "my_api_key";
        o.Dataset = "my_dataset";
    }
    .Build();
```

This setup generates OpenTelemetry traces with the following process tags:

```
honeycomb.distro.runtime_version: 5.0.15
honeycomb.distro.version: 0.20.0-beta
service.instance.id: 2d792d58-0679-40de-9722-4bae67d57a31
service.version: {unknown_service_version}
```
It lacks "deployment.environment production"

If I remove AddHoneycomb from the tracerProvider build steps, then the following process tags are generated:

```
deployment.environment: production
service.instance.id: MACHINE_NAME
```

Looks like Honeycomb replaces resource attributes with its own. "deployment.environment" is used by OpenTelemetry and helps differentiate between traces in different deployment environments. So it's important that Honeycomb doesn't overwrite or replaces these attributes.

**Comment by MikeGoldsmith** [comment]
Hi @object - thanks for raising the bug. We'll take a look and report back.

**Comment by object** [comment]
@MikeGoldsmith  But this is the standard way of assigning attributes, and OpenTelemetry defines many standard attributes that are usually assigned in such a way (there are plenty of examples with such code).

Here are attributes that OpenTelemetry recommends to use:
https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions

So I think it's problematic if Honeycomb deletes them. If you see no way of retaining them, then you probably should extend your library to allow setting those attributes there.

**Comment by MikeGoldsmith** [comment]
Yes, I agree it's not ideal and we'll look at alternative ways to support additional attributes beyond the ones set via the distro.

FYI I think this is a design issue of the OpenTelemetry SDK where it does not allow subsequent builders to add resource attributes, you must set the resource again. If the SDK allowed adding attributes to the configured Resource we wouldn't need to set it again.

**Comment by object** [comment]
I wasn't aware of that. I thought one could add to an existing resource. But if so, then there only way to retain the attributes already set would be to let the user to reassign them using Honeycomb options. Far from ideal indeed.

**Comment by MikeGoldsmith** [comment]
Yeah, one way to solve this use case would be to pass the ResourceBuilder or prebuilt Resource or ResourceBuilder into the Addhoneycomb via a HoneycombOptions property.

We'll have a look to see if we can figure out a solution 👍🏻

**Comment by object** [comment]
This will solve it for Honeycomb exporter but in case an application uses several OpenTelemetry exporters, others will miss these resource attributes.

**Comment by MikeGoldsmith** [comment]
Yeah, it may not work for more advanced setups, although the Honeycomb distro is aimed at beginners.

An alternative might be to add an extension method for the ResourceBuilder directly to add the Honeycomb attributes. This is challenging because a user would need remember to hook in multiple times.

eg
```csharp
ResourceBuilder.CreateDefault()
    .AddAttributes(new Dictionary<string, object>
    {
        {"deployment.environment", "production"}
    })
    .AddService(serviceName: serviceName, serviceVersion: serviceVersion))
    .AddHoneycomb() // here we add honeycomb specific attributes
    .Build()
```

**Comment by object** [comment]
This is what I was doing, and as long as I added Honeycomb the attributes for Elastic were erased. So it's a problem.

**Comment by MikeGoldsmith** [comment]
Sorry, that wasn't clear. The above example was for the ResoureBuilder, with a new AddHoneycomb extension method that only sets attributes. We would then not set attributes during the TracerBuilder's AddHoneycomb extension method.

Using your original example, it would look like this:

```csharp
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
    .AddSource(serviceName)
    .SetResourceBuilder(
        ResourceBuilder.CreateDefault()
            .AddAttributes(new Dictionary<string, object>
            {
                {"deployment.environment", "production"}
            })
            .AddHoneycomb() // new extension method for adding attributes
            .AddService(serviceName: serviceName, serviceVersion: serviceVersion))
    .AddHttpClientInstrumentation()
    .AddJaegerExporter(o =>
    {
        o.AgentHost = "localhost";
        o.AgentPort = 6831;
    })
    .AddConsoleExporter()
    .AddHoneycomb(o => // no longer sets attributes
    {
        o.ServiceName = serviceName;
        o.ApiKay = "my_api_key";
        o.Dataset = "my_dataset";
    }
    .Build();
```

I'm not certain if that will work yet but will look into it.

**Comment by object** [comment]
Ah I see. Yes that might work.

**Comment by MikeGoldsmith** [comment]
It's also worth pointing out, that the current AddHoneycomb method subscribes the source using the service name, sets the OTel service name & version attribute and enabled HTTP instrumentation, so your example could be simplified to:

```csharp
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
    .SetResourceBuilder(
        ResourceBuilder.CreateDefault()
            .AddAttributes(new Dictionary<string, object>
            {
                {"deployment.environment", "production"}
            })
    .AddJaegerExporter(o =>
    {
        o.AgentHost = "localhost";
        o.AgentPort = 6831;
    })
    .AddConsoleExporter()
    .AddHoneycomb(o =>
    {
        o.ServiceName = serviceName;
        o.ApiKay = "my_api_key";
        o.Dataset = "my_dataset";
    }
    .Build();
```

I agree it does not solve the problem of additional attributes, but does show that the AddHoneycomb method configures a bit more.

**Comment by object** [comment]
@MikeGoldsmith I tried the latest Honeycomb.OpenTelemetry Nuget package (0.21.0-beta), but the new extension method on ResourceBuilder AddHoneycomb() was not available. Is this change not released yet?

**Comment by MikeGoldsmith** [comment]
The change was to add a ResourceBuilder property to HoneycombOptions. You'd create the resource builder and add your custom attributes, then pass it in on HoneycombOptions so we can also add things to it before it's set.

```
var resourceBuilder = ResourceBuilder.CreateDefault()
  .AddAttributes(new Dictionary<string, object>
  {
    {"deployment.environment", "production"}
  });
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
  .AddHoneycomb(o =>
  {
    o.ServiceName = serviceName;
    o.ApiKay = "my_api_key";
    o.Dataset = "my_dataset";
    o.ResourceBuilder = resourceBuilder;
  }
  .Build();
```

**Comment by object** [comment]
Thanks, that worked!
