### ISSUE TITLE
1.0 docs updates

### ISSUE THREAD

**Issue by cartermp** [honeycombio/honeycomb-opentelemetry-dotnet#267]
When we're ready to go GA, we also need to update docs + in-app quickstart to reference the API changes we made. Small lift, but a thing.

PRs:
- https://github.com/honeycombio/hound/pull/11390

**Comment by cartermp** [comment]
Linky: https://github.com/honeycombio/docs/pull/1464

**Comment by MikeGoldsmith** [comment]
Updated both Hound quickstart guide and docs with recent changes (eg namespace changes & GetHoneycombOptions ext method).

Both are now aligned with final GA state 🎉
