### ISSUE TITLE
Smoke tests fail to run in CI

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-opentelemetry-dotnet#277]
Smoke tests are failing to run in CI. The error looks like the aspnetcore example app is failing to wire up the Tracer correctly so it fails to inject into WeatherForecast controller. 

Locally, it hangs and doesn't return. I think it's stuck waiting for trace data to arrive.

**Additional context**
[Recent CI build](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-dotnet/1038/workflows/2adf74f2-6be8-4259-8183-3c31bf8eae46/jobs/1601)

**Comment by cartermp** [comment]
Hmmm, locally this works. I noticed that that dockerfile curls against `http` whereas when I run this locally, I curl `https`. Could that be it?

**Comment by cartermp** [comment]
Blegh, looks like that wasn't it. Definitely something different about the dockerized environment compared to a local one on my machine.

**Comment by JamieDanielson** [comment]
Hm. I may have missed something somewhere, but this failure seems intermittent or this has been fixed.

**Comment by pkanal** [comment]
I'm finding that this seems to only fail on `main`? I might start looking into this a little more.

**Comment by JamieDanielson** [comment]
> I'm finding that this seems to only fail on `main`? I might start looking into this a little more.

Looks like it's [passed in the last 3 merges to main](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-dotnet?branch=main) 🎉  I think it's okay to hold off on researching further until the next merge to main and see how it goes. If it passes, let's close and re-open if flakiness returns.
