### ISSUE TITLE
Enable metrics by default

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-dotnet#333]
**Is your feature request related to a problem? Please describe.**

Currently metrics are disabled by default; we want to enable by default.

**Describe the solution you'd like**

* to enable by default, [adjust the logic](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs#L36) that currently only adds the exporter and meter when dataset is set
* add a warning for missing metrics dataset (similar to missing trace service name)
* set a default metrics dataset of unknown_metrics

**Comment by MikeGoldsmith** [comment]
After further discussion, we do not want to enable metrics by default. Instead, we still require a metrics dataset be set to enable metrics.
