### ISSUE TITLE
Adding provider resets sampler

### ISSUE THREAD

**Issue by pbiggar** [honeycombio/honeycomb-opentelemetry-dotnet#350]
**Versions**

- .NET runtime & version (eg .NET Core, .NET Framework): 6.0.300
- Honeycomb OpenTelemetry Distribution: 0.18.0-beta

**Steps to reproduce**

1. Add sampler to a TracerProviderBuilder
2. Add honeycomb to the TracerProviderBuilder
-> The sampler is no longer used (ShouldSample is no longer called)

**Additional context**

Does not happen when just adding a ConsoleExporter instead of honeycomb

[Fixed](https://github.com/darklang/classic-dark/pull/23/files#diff-637e2f1241c203f1ef1018b27142a6136a5796e04952b07b8a1eaa8b65ea14f2L339) by added the Sampler AFTER adding Honeycomb.

**Comment by MikeGoldsmith** [comment]
This is a known issue with the OpenTelemetry SDK builder pattern. There is no way to know if a sampler has already been set, so the last one always wins. Ideally, there was a sampler already set, it would warn to say it's being overwritten.

Unfortunately, other than documenting the behaviour, there isn't much we can do about it here as  an Otel SDK decision.
