### ISSUE TITLE
The official OpenTelemetry .NET package renamed `AspNetCoreInstrumentationOptions` to `AspNetCoreTraceInstrumentationOptions`

### ISSUE THREAD

**Issue by ChrisDusyk** [honeycombio/honeycomb-opentelemetry-dotnet#374]
**Versions**

- .NET runtime & version (eg .NET Core, .NET Framework): .NET 8
- Honeycomb OpenTelemetry Distribution: `Honeycomb.OpenTelemetry.Instrumentation.AspNetCore` and `Honeycomb.OpenTelemetry.CommonInstrumentations` version `0.29.0-beta`, `Honeycomb.OpenTelemetry` version `1.5.0`

**Steps to reproduce**

1. Install dependencies: 
    - `Honeycomb.OpenTelemetry.Instrumentation.AspNetCore@0.29.0-beta`, `Honeycomb.OpenTelemetry.CommonInstrumentations@0.29.0-beta`, and `Honeycomb.OpenTelemetry@1.5.0`
    - `OpenTelemetry.Api.*` and `OpenTelemetry.Instrumentation.*` versions `1.7.x`
2. Instrument an ASP.NET 8 application in startup:
    ```C#
    // Add OpenTelemetry config
    var honeycombConfig = builder.Configuration.GetHoneycombOptions();
    builder.Services
	.AddOpenTelemetry()
	.UseAzureMonitor()
	.WithTracing(otelBuilder =>
	{
		otelBuilder
			.AddHoneycomb(honeycombConfig)
			.AddCommonInstrumentations();
	});

    builder.Services.AddSingleton(TracerProvider.Default.GetTracer(honeycombConfig.ServiceName));
    ```
3. Attempt to start application. It will fail at runtime with this error:
    
    ![image](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/assets/2198696/0da7cf98-947b-433b-b0ad-a86cc91e4765)

**Additional context**

After picking apart what `.AddCommonInstrumentations()` sets up, I concluded this error was a bit misleading and the core problem is that `AspNetCoreInstrumentationOptions` has been renamed to `AspNetCoreTraceInstrumentationOptions` as part of https://github.com/open-telemetry/opentelemetry-dotnet/pull/5108, which has been released in `1.7.0` of the OpenTelemetry .NET distro packages.

I have an example of where this happens in a repo I was building to do a demo: https://github.com/ChrisDusyk/ObservabilityDemo/blob/main/ObservabilityDemo.Server/Program.cs

**Comment by TylerHelmuth** [comment]
@ChrisDusyk we are only using Instrumentation version `1.6.0-beta.3` since any later version comes with the stable HTTP semantic convention breaking changes.  See https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/365. I expect we'll be on `1.6.0-beta.3` for 6 months to give users time to use `OTEL_SEMCONV_STABILITY_OPT_IN` to handle the transition.  For more details checkout https://docs.honeycomb.io/troubleshoot/product-lifecycle/recommended-migrations/migrate-to-opentelemetry-semantic-conventions/.

**Comment by ChrisDusyk** [comment]
@TylerHelmuth sounds good, thanks for the explanation. Would it be possible to call that out in docs right now as well? Since `Honeycomb.OpenTelemetry.Instrumentation.AspNetCore` depends on `OpenTelemetry.Instrumentation.AspNetCore (>= 1.6.0-beta.3)`, NuGet will automatically resolve it to `1.7.1` since that fits in the accepted dependency range. I know this is heavily on the OpenTelemetry folks for introducing breaking changes in a minor version increase, but right now the docs as written will result in the error I ran into.
