### ISSUE TITLE
Manage the fact that we have an old package at the same name

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-dotnet#54]
Document that the old package is now superseded by the new stuff.

**Comment by MikeGoldsmith** [comment]
We put a comment into the repo README and don't have anything on the docs site about the previous package.

@bdarfler do you think we need to add more?

**Comment by bdarfler** [comment]
I think that's sufficient but we should run this by the team at sync or in slack first.

**Comment by MikeGoldsmith** [comment]
We also added notes in both internal and Pollinators - happy for this to be closed.
