### ISSUE TITLE
Update OTel packages to GA releases

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-opentelemetry-dotnet#61]
The OpenTelemetry .NET core packages used in this wrapper are all pre-release packages. A nuget package cannot be published as GA if it contains pre-release dependencies.

The [1.1.0 core packages](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.1.0) have been released.
The [1.0.0 instrumentation packages](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/1.0.0-rc7) are currently at rc7

We should upgrade to the latest 1.1.0 core packages and 1.0.0-rc7 packages.

**Comment by cartermp** [comment]
> A nuget package cannot be published as GA if it contains pre-release dependencies.

Argh, that could complicate things. I could see the upstream instrumentation libraries staying in preview longer. We'll want to chat with 'em about this when we're in our GA push.

**Comment by cartermp** [comment]
For us to do this, we'll need to change our TFMs. Instrumentation for ASP.NET Core is not longer .NET Standard 2.0.

For us to continue supporting .NET Framework, we'll likely need to rip out .NET Standard and just multitarget the .NET versions.

**Comment by MikeGoldsmith** [comment]
Separating the instrumentation packages into a new project will allow us to create a GA version of our distro.
