### ISSUE TITLE
Make it more clear what version of OTel this is built against

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-dotnet#93]
Since we will be versioning independently of OTel due to the additional functionality we are adding we want to make it more easily discoverable what version of OTel we are building against.

Maybe at the top of the README? Maybe a badge?

**Comment by cartermp** [comment]
Generally I'm in favor of whatever can be automated. Badge in the README would be my preference. Note that in NuGet, the UI will also present this dependency info, so I think it's mostly about communicating it clearly in the README here.
